apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: anibe
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: api
