apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
  namespace: anibe
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-storage
  namespace: anibe
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /data/mongo-storage/

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
  namespace: anibe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: mongodb-disk
            fsType: ext4
