apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
  namespace: anibe
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis

---

apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis
  name: redis-controller
  namespace: anibe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - image: redis
        name: redis
        ports:
        - name: redis
          containerPort: 6379
          hostPort: 6379
