version: '2.1'

services:
  api:
    image: api
    build: .
    environment:
      NODE_ENV: production
      SENDGRID_KEY: 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
      MASTER_KEY: V3T0wJL6wuVk502cPq1cN7mgN1FJvYdR
      JWT_SECRET: aCjiMuoMpAO2dfk0koKO1uJJ5aUCyaVv
    links:
      - mongo
      - nginx

  mongo:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/mongodb
    volumes:
      - /data/mongodb:/data/mongodb

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./cfg/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
