version: 2
jobs:

  lint:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - run:
          command: yarn test --coverage
          name: "Unit test"

  build:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "19:9a:bf:7f:ce:ea:3a:15:01:5f:e0:a6:16:23:b3:95"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: deploy app
          command: ssh $SSH_USERNAME@$SSH_HOST "cd ~/anibe.api && git checkout master && git pull && yarn && pm2 update"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
  build-test-and-deploy:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - lint
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - lint
           - test
      - deploy:
          requires:
            - lint
            - test
            - hold
          filters:
            branches:
              only: master
