version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn lint

  test:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm i --dev

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          command: yarn test --coverage
          name: "Unit test"

  build:
    docker:
      - image: circleci/node:8.9.0
    working_dirictory: ~/repo

    steps:
      - run: "echo todo"
      # - checkout
      # - restore_cache:
      #     keys:
      #       - v1-dependencies-{{ checksum "package.json" }}
      #       - v1-dependencies-

      # - run: yarn install

      # - save_cache:
      #     paths:
      #       - node_modules
      #     key: v1-dependencies-{{ checksum "package.json" }}

      # - run:
      #     command: yarn docs
      #     name: "Unit test"

      # - store_test_results:
      #   path: coverage

  deploy:
    branches:
      only:
        - master
    working_directory: ~/repo
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "yo:ur:ss:hf:in:ge:rp:ri:nt"
      - run:
          name: fix host authenticity for production server
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: deploy app
          command: ssh $SSH_USERNAME@$SSH_HOST "cd ~/anibe.api && git checkout master && git pull && yarn && pm2 update"

workflows:
  version: 2
  build_and_test:
    jobs:
      - lint
      # - test:
      #     requires:
      #       - lint
      - deploy:
          requires:
            - lint
            # - test
          filters:
            branches:
              only: master
